spring:
  application:
    name: graduation-design-user
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: http://localhost:8848
        username: nacos
        password: nacos
        namespace: public
  datasource:
    url: 'jdbc:mysql://localhost:3306/user?
            createDatabaseIfNotExist=true
            &serverTimezone=Asia/Shanghai'
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  redis:
    host: localhost
    port: 6379
    password: foobared
    database: 1
server:
  port: 8084

logging:
  level:
    root: warn
    com:
      example: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'

jackson:
  default-property-inclusion: non_null
#cache:
#  caffeine: # 在代码注入缓存管理器，此处配置无效
#    spec: expireAfterWrite=1d, maximumSize=200

my:
  secretkey: R28K42ZEJ8LWRHU5
  salt: 636eac2534bcfcb0

helpline: http://graduation-design-information/api/helpline
news: http://graduation-design-information/api/news
animal: http://graduation-design-animal/api/user/animal
question: http://graduation-design-question/api/question