spring:
  application:
    name: graduation-design-information
  datasource:
    url: 'jdbc:mysql://localhost:3306/information?
            createDatabaseIfNotExist=true
            &serverTimezone=Asia/Shanghai'
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: http://localhost:8848
        username: nacos
        password: nacos
        namespace: public
  redis:
    host: localhost
    port: 6379
    password: foobared
    database: 1
logging:
  level:
    root: warn
    com:
      example: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'

jackson:
  default-property-inclusion: non_null
#cache:
#  caffeine: # 在代码注入缓存管理器，此处配置无效
#    spec: expireAfterWrite=1d, maximumSize=200

my:
  secretkey: R28K42ZEJ8LWRHU5
  salt: 636eac2534bcfcb0
server:
  port: 8080